"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "ar" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ar")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage) {
      setLanguageState(savedLanguage)
      document.documentElement.lang = savedLanguage
      document.documentElement.dir = savedLanguage === "ar" ? "rtl" : "ltr"
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("language", lang)
    document.documentElement.lang = lang
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    // Common
    loading: "جاري التحميل...",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    add: "إضافة",
    submit: "إرسال",
    search: "بحث",
    filter: "تصفية",
    close: "إغلاق",
    confirm: "تأكيد",
    yes: "نعم",
    no: "لا",
    actions: "الإجراءات",
    view: "عرض",
    download: "تحميل",
    upload: "رفع",
    send: "إرسال",
    back: "رجوع",
    next: "التالي",
    previous: "السابق",
    select: "اختيار",
    selectAll: "تحديد الكل",
    clear: "مسح",
    reset: "إعادة تعيين",
    apply: "تطبيق",
    create: "إنشاء",
    update: "تحديث",
    remove: "إزالة",

    // Roles
    student: "طالب",
    supervisor: "مشرف",
    coordinator: "منسق",
    admin: "مدير",

    // Sidebar Navigation
    dashboard: "لوحة التحكم",
    myProject: "مشروعي",
    tasks: "المهام",
    meetings: "الاجتماعات",
    files: "الملفات",
    announcements: "الإعلانات",
    discussions: "المناقشات",
    messages: "الرسائل",
    grades: "الدرجات",
    notifications: "الإشعارات",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    profile: "الملف الشخصي",
    projects: "المشاريع",
    students: "الطلاب",
    supervisors: "المشرفين",
    reports: "التقارير",
    archive: "الأرشيف",
    assignSupervisors: "تعيين المشرفين",
    projectIdeas: "أفكار المشاريع",
    evaluations: "التقييمات",
    tasksAndEvaluation: "المهام والتقييم",

    // Platform
    platformTitle: "منصة المشاريع",
    graduationProjectsPlatform: "منصة مشاريع التخرج",
    mainMenu: "القائمة الرئيسية",
    mainNavDescription: "قائمة التنقل الرئيسية للوصول إلى جميع أقسام النظام",

    // Auth Pages
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    forgotPassword: "نسيت كلمة المرور؟",
    resetPassword: "إعادة تعيين كلمة المرور",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    name: "الاسم",
    phone: "رقم الهاتف",
    studentId: "الرقم الجامعي",
    employeeId: "الرقم الوظيفي",
    department: "القسم",
    role: "الدور",
    loginButton: "تسجيل الدخول",
    loggingIn: "جاري تسجيل الدخول...",
    createAccount: "إنشاء حساب",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    dontHaveAccount: "ليس لديك حساب؟",
    invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة",

    // Dashboard
    welcome: "مرحباً",
    welcomeBack: "مرحباً بعودتك",
    overviewText: "إليك نظرة عامة على مشروع التخرج الخاص بك",
    supervisorOverview: "نظرة عامة على المشاريع التي تشرف عليها",
    coordinatorOverview: "نظرة عامة على جميع المشاريع",
    totalTasks: "إجمالي المهام",
    completedTasks: "المهام المكتملة",
    upcomingMeetings: "الاجتماعات القادمة",
    projectProgress: "تقدم المشروع",
    recentTasks: "المهام الأخيرة",
    recentNotifications: "الإشعارات الأخيرة",
    latestUpdates: "آخر التحديثات",
    noTasksYet: "لا توجد مهام حالياً",
    noDataFound: "لم يتم العثور على بيانات المستخدم",
    errorLoadingData: "حدث خطأ أثناء تحميل البيانات",
    errorOccurred: "حدث خطأ",
    welcomeToplatform: "مرحباً بك في المنصة",
    startByAddingProject: "ابدأ بإضافة مشروعك ومتابعة المهام",

    // Project Page
    projectDetails: "تفاصيل مشروع التخرج الخاص بك",
    myProjectDetails: "تفاصيل مشروعي",
    submitProjectIdea: "تقديم فكرة مشروع",
    submittedProjectIdeas: "أفكار المشاريع المقدمة",
    projectIdeasStatus: "حالة أفكار المشاريع التي قدمتها",
    submissionDate: "تاريخ التقديم",
    approved: "مقبول",
    rejected: "مرفوض",
    underReview: "قيد المراجعة",
    noProjectAssigned: "لم يتم تعيين مشروع بعد",
    projectSubmittedUnderReview: "تم تقديم فكرة المشروع وهي قيد المراجعة. سيتم إشعارك بالقرار قريباً.",
    submitOrWait: "قدم فكرة مشروع أو انتظر تعيين مشروع من المنسق الأكاديمي",
    active: "نشط",
    completed: "مكتمل",
    pending: "معلق",
    inProgress: "قيد التنفيذ",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    expectedDeliveryDate: "تاريخ التسليم المتوقع",
    notSpecified: "غير محدد",
    tasksAndAssignments: "التسليمات والواجبات",
    discussionForum: "منتدى النقاش",
    evaluationsAndResults: "التقييمات والنتائج",
    supervisorInfo: "معلومات المشرف على المشروع",
    contactSupervisor: "التواصل مع المشرف",
    projectObjectives: "أهداف المشروع",
    noObjectivesYet: "لم يتم تحديد أهداف بعد",
    projectTitle: "عنوان المشروع",
    projectDescription: "وصف المشروع",
    projectStatus: "حالة المشروع",
    projectType: "نوع المشروع",

    // Tasks
    taskTitle: "عنوان المهمة",
    taskDescription: "وصف المهمة",
    taskStatus: "حالة المهمة",
    taskPriority: "أولوية المهمة",
    dueDate: "تاريخ الاستحقاق",
    assignedTo: "مسندة إلى",
    assignedBy: "مسندة من",
    new: "جديدة",
    high: "عالية",
    medium: "متوسطة",
    low: "منخفضة",
    urgent: "عاجل",
    addTask: "إضافة مهمة",
    editTask: "تعديل مهمة",
    deleteTask: "حذف مهمة",
    completeTask: "إكمال المهمة",
    markAsComplete: "تعيين كمكتملة",
    markAsIncomplete: "تعيين كغير مكتملة",

    // Meetings
    meetingTitle: "عنوان الاجتماع",
    meetingDescription: "وصف الاجتماع",
    meetingDate: "تاريخ الاجتماع",
    meetingTime: "وقت الاجتماع",
    meetingLocation: "موقع الاجتماع",
    meetingLink: "رابط الاجتماع",
    meetingStatus: "حالة الاجتماع",
    scheduled: "مجدول",
    canceled: "ملغي",
    addMeeting: "إضافة اجتماع",
    editMeeting: "تعديل اجتماع",
    deleteMeeting: "حذف اجتماع",
    joinMeeting: "الانضمام للاجتماع",
    scheduleMeeting: "جدولة اجتماع",
    noMeetingsYet: "لا توجد اجتماعات حالياً",
    upcomingMeeting: "اجتماع قادم",
    pastMeeting: "اجتماع سابق",

    // Files
    fileName: "اسم الملف",
    fileSize: "حجم الملف",
    fileType: "نوع الملف",
    uploadDate: "تاريخ الرفع",
    uploadedBy: "رفع بواسطة",
    addFile: "إضافة ملف",
    uploadFile: "رفع ملف",
    downloadFile: "تحميل الملف",
    deleteFile: "حذف الملف",
    noFilesYet: "لا توجد ملفات حالياً",
    dragAndDrop: "اسحب وأفلت الملف هنا",
    orClickToSelect: "أو انقر للاختيار",

    // Announcements
    announcementTitle: "عنوان الإعلان",
    announcementContent: "محتوى الإعلان",
    announcementDate: "تاريخ الإعلان",
    announcementScope: "نطاق الإعلان",
    addAnnouncement: "إضافة إعلان",
    editAnnouncement: "تعديل إعلان",
    deleteAnnouncement: "حذف إعلان",
    allProjects: "جميع المشاريع",
    oneSemesterProjects: "مشاريع فصل واحد",
    twoSemesterProjects: "مشاريع فصلين",
    other: "أخرى",
    noAnnouncementsYet: "لا توجد إعلانات حالياً",

    // Discussions
    discussionTitle: "عنوان النقاش",
    discussionContent: "محتوى النقاش",
    discussionDate: "تاريخ النقاش",
    addDiscussion: "إضافة نقاش",
    reply: "رد",
    replies: "الردود",
    noDiscussionsYet: "لا توجد نقاشات حالياً",
    startDiscussion: "ابدأ نقاشاً جديداً",
    noProject: "لا يوجد مشروع",
    mustBeInProjectForDiscussions: "يجب أن تكون مسجلاً في مشروع للوصول إلى النقاشات",
    shareIdeasWithTeam: "شارك الأفكار والأسئلة مع فريق المشروع",
    newDiscussion: "نقاش جديد",
    createNewDiscussion: "إنشاء نقاش جديد",
    enterDiscussionTitle: "أدخل عنوان النقاش",
    explainDiscussionInDetail: "اشرح موضوع النقاش بالتفصيل",
    tags: "الوسوم",
    tagsExample: "مثال: تقني, تقرير, مراجعة (افصل بفاصلة)",
    separateTagsWithComma: "افصل الوسوم بفاصلة",
    createDiscussion: "إنشاء النقاش",
    all: "الكل",
    open: "مفتوح",
    closed: "مغلق",
    noDiscussions: "لا توجد نقاشات",
    pinned: "مثبت",
    errorFetchingDiscussions: "حدث خطأ أثناء تحميل النقاشات",
    fillAllRequiredFields: "يرجى ملء جميع الحقول المطلوبة",
    mustBeInProjectToCreateDiscussion: "يجب أن تكون مسجلاً في مشروع لإنشاء نقاش",
    discussionCreatedSuccessfully: "تم إنشاء النقاش بنجاح",
    errorCreatingDiscussion: "حدث خطأ أثناء إنشاء النقاش",
    error: "حدث خطأ",
    fewMinutesAgo: "منذ دقائق",
    hoursAgo: "منذ {hours} ساعة",
    oneDayAgo: "منذ يوم واحد",
  },
  en: {
    // Common
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    submit: "Submit",
    search: "Search",
    filter: "Filter",
    close: "Close",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    actions: "Actions",
    view: "View",
    download: "Download",
    upload: "Upload",
    send: "Send",
    back: "Back",
    next: "Next",
    previous: "Previous",
    select: "Select",
    selectAll: "Select All",
    clear: "Clear",
    reset: "Reset",
    apply: "Apply",
    create: "Create",
    update: "Update",
    remove: "Remove",

    // Roles
    student: "Student",
    supervisor: "Supervisor",
    coordinator: "Coordinator",
    admin: "Admin",

    // Sidebar Navigation
    dashboard: "Dashboard",
    myProject: "My Project",
    tasks: "Tasks",
    meetings: "Meetings",
    files: "Files",
    announcements: "Announcements",
    discussions: "Discussions",
    messages: "Messages",
    grades: "Grades",
    notifications: "Notifications",
    settings: "Settings",
    logout: "Logout",
    profile: "Profile",
    projects: "Projects",
    students: "Students",
    supervisors: "Supervisors",
    reports: "Reports",
    archive: "Archive",
    assignSupervisors: "Assign Supervisors",
    projectIdeas: "Project Ideas",
    evaluations: "Evaluations",
    tasksAndEvaluation: "Tasks and Evaluation",

    // Platform
    platformTitle: "Projects Platform",
    graduationProjectsPlatform: "Graduation Projects Platform",
    mainMenu: "Main Menu",
    mainNavDescription: "Main navigation menu to access all system sections",

    // Auth Pages
    login: "Login",
    register: "Register",
    forgotPassword: "Forgot Password?",
    resetPassword: "Reset Password",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    name: "Name",
    phone: "Phone",
    studentId: "Student ID",
    employeeId: "Employee ID",
    department: "Department",
    role: "Role",
    loginButton: "Login",
    loggingIn: "Logging in...",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    invalidCredentials: "Invalid email or password",

    // Dashboard
    welcome: "Welcome",
    welcomeBack: "Welcome back",
    overviewText: "Here's an overview of your graduation project",
    supervisorOverview: "Overview of projects you supervise",
    coordinatorOverview: "Overview of all projects",
    totalTasks: "Total Tasks",
    completedTasks: "Completed Tasks",
    upcomingMeetings: "Upcoming Meetings",
    projectProgress: "Project Progress",
    recentTasks: "Recent Tasks",
    recentNotifications: "Recent Notifications",
    latestUpdates: "Latest Updates",
    noTasksYet: "No tasks yet",
    noDataFound: "User data not found",
    errorLoadingData: "Error loading data",
    errorOccurred: "An error occurred",
    welcomeToplatform: "Welcome to the Platform",
    startByAddingProject: "Start by adding your project and tracking tasks",

    // Project Page
    projectDetails: "Your graduation project details",
    myProjectDetails: "My Project Details",
    submitProjectIdea: "Submit Project Idea",
    submittedProjectIdeas: "Submitted Project Ideas",
    projectIdeasStatus: "Status of your submitted project ideas",
    submissionDate: "Submission Date",
    approved: "Approved",
    rejected: "Rejected",
    underReview: "Under Review",
    noProjectAssigned: "No project assigned yet",
    projectSubmittedUnderReview:
      "Project idea has been submitted and is under review. You will be notified of the decision soon.",
    submitOrWait: "Submit a project idea or wait for project assignment from the academic coordinator",
    active: "Active",
    completed: "Completed",
    pending: "Pending",
    inProgress: "In Progress",
    startDate: "Start Date",
    endDate: "End Date",
    expectedDeliveryDate: "Expected Delivery Date",
    notSpecified: "Not Specified",
    tasksAndAssignments: "Tasks and Assignments",
    discussionForum: "Discussion Forum",
    evaluationsAndResults: "Evaluations and Results",
    supervisorInfo: "Project supervisor information",
    contactSupervisor: "Contact Supervisor",
    projectObjectives: "Project Objectives",
    noObjectivesYet: "No objectives set yet",
    projectTitle: "Project Title",
    projectDescription: "Project Description",
    projectStatus: "Project Status",
    projectType: "Project Type",

    // Tasks
    taskTitle: "Task Title",
    taskDescription: "Task Description",
    taskStatus: "Task Status",
    taskPriority: "Task Priority",
    dueDate: "Due Date",
    assignedTo: "Assigned To",
    assignedBy: "Assigned By",
    new: "New",
    high: "High",
    medium: "Medium",
    low: "Low",
    urgent: "Urgent",
    addTask: "Add Task",
    editTask: "Edit Task",
    deleteTask: "Delete Task",
    completeTask: "Complete Task",
    markAsComplete: "Mark as Complete",
    markAsIncomplete: "Mark as Incomplete",

    // Meetings
    meetingTitle: "Meeting Title",
    meetingDescription: "Meeting Description",
    meetingDate: "Meeting Date",
    meetingTime: "Meeting Time",
    meetingLocation: "Meeting Location",
    meetingLink: "Meeting Link",
    meetingStatus: "Meeting Status",
    scheduled: "Scheduled",
    canceled: "Canceled",
    addMeeting: "Add Meeting",
    editMeeting: "Edit Meeting",
    deleteMeeting: "Delete Meeting",
    joinMeeting: "Join Meeting",
    scheduleMeeting: "Schedule Meeting",
    noMeetingsYet: "No meetings yet",
    upcomingMeeting: "Upcoming Meeting",
    pastMeeting: "Past Meeting",

    // Files
    fileName: "File Name",
    fileSize: "File Size",
    fileType: "File Type",
    uploadDate: "Upload Date",
    uploadedBy: "Uploaded By",
    addFile: "Add File",
    uploadFile: "Upload File",
    downloadFile: "Download File",
    deleteFile: "Delete File",
    noFilesYet: "No files yet",
    dragAndDrop: "Drag and drop file here",
    orClickToSelect: "Or click to select",

    // Announcements
    announcementTitle: "Announcement Title",
    announcementContent: "Announcement Content",
    announcementDate: "Announcement Date",
    announcementScope: "Announcement Scope",
    addAnnouncement: "Add Announcement",
    editAnnouncement: "Edit Announcement",
    deleteAnnouncement: "Delete Announcement",
    allProjects: "All Projects",
    oneSemesterProjects: "One Semester Projects",
    twoSemesterProjects: "Two Semester Projects",
    other: "Other",
    noAnnouncementsYet: "No announcements yet",

    // Discussions
    discussionTitle: "Discussion Title",
    discussionContent: "Discussion Content",
    discussionDate: "Discussion Date",
    addDiscussion: "Add Discussion",
    reply: "Reply",
    replies: "Replies",
    noDiscussionsYet: "No discussions yet",
    startDiscussion: "Start a new discussion",
    noProject: "No Project",
    mustBeInProjectForDiscussions: "You must be enrolled in a project to access discussions",
    shareIdeasWithTeam: "Share ideas and questions with the project team",
    newDiscussion: "New Discussion",
    createNewDiscussion: "Create New Discussion",
    enterDiscussionTitle: "Enter discussion title",
    explainDiscussionInDetail: "Explain the discussion topic in detail",
    tags: "Tags",
    tagsExample: "Example: technical, report, review (separated by comma)",
    separateTagsWithComma: "Separate tags with comma",
    createDiscussion: "Create Discussion",
    all: "All",
    open: "Open",
    closed: "Closed",
    noDiscussions: "No Discussions",
    pinned: "Pinned",
    errorFetchingDiscussions: "Error fetching discussions",
    fillAllRequiredFields: "Please fill all required fields",
    mustBeInProjectToCreateDiscussion: "You must be enrolled in a project to create a discussion",
    discussionCreatedSuccessfully: "Discussion created successfully",
    errorCreatingDiscussion: "Error creating discussion",
    error: "An error occurred",
    fewMinutesAgo: "A few minutes ago",
    hoursAgo: "{hours} hours ago",
    oneDayAgo: "One day ago",
  },
}
